#### spring相关配置
spring:
  application:
    name: mall-cart #应用名称
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
server:
  port: 8008

#logostash
logging:
  config: classpath:logback-spring.xml