server:
  port: 8000

spring:
  application:
    name: mall-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务注册
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: mall-admin
          uri: lb://mall-admin #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-admin/**
        - id: mall-auth
          uri: lb://mall-auth #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-auth/**
        - id: mall-goods
          uri: lb://mall-goods #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-goods/**
        - id: mall-file
          uri: lb://mall-file #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-file/**
        - id: mall-coupon
          uri: lb://mall-coupon #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-coupon/**
  mvc:
    servlet:
      load-on-startup: 1
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: false
ribbon:
  eager-load:
    enabled: true
    clients: mall-gateway

#白名单
white:
  list:
    urls: #安全路径白名单
      - /mall-admin/captcha/get #验证码接口
      - /mall-admin/captcha/check
      - /mall-admin/system/admin/login
