server:
  port: 8000

spring:
  application:
    name: mall-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 49.234.85.17:8848 #nacos服务注册
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: mall-admin
          uri: lb://mall-admin #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-admin/**
        - id: mall-auth
          uri: lb://mall-auth #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-auth/**
        - id: mall-goods
          uri: lb://mall-goods #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-goods/**
        - id: mall-file
          uri: lb://mall-file #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-file/**
        - id: mall-coupon
          uri: lb://mall-coupon #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-coupon/**
        - id: mall-seckill
          uri: lb://mall-seckill #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-seckill/**
        - id: mall-member
          uri: lb://mall-member #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-member/**
        - id: mall-cart
          uri: lb://mall-cart #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-cart/**
        - id: mall-order
          uri: lb://mall-order #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-order/**
        - id: mall-payment
          uri: lb://mall-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-payment/**
        - id: mall-search
          uri: lb://mall-search #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-search/**
        - id: mall-log
          uri: lb://mall-log #匹配后提供服务的路由地址
          predicates:
            - Path=/mall-log/**
  mvc:
    servlet:
      load-on-startup: 1
feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
  hystrix:
    enabled: false
ribbon:
  eager-load:
    enabled: true
    clients:
      - mall-file
      - mall-order
      - mall-member
      - mall-admin
      - mall-goods
      - mall-seckill
      - mall-security-oauth2
      - mall-log
      - mall-payment
      - mall-gateway
      - mall-coupon
      - mall-cart
      - mall-search

#logostash
logging:
  config: classpath:logback-spring.xml

elk:
  kafka:
    appender:
      servers: '123.60.173.14:9092'
      topic: readygo-mall-logs

#白名单
white:
  list:
    urls: #安全路径白名单
      - /mall-admin/captcha/get #验证码接口
      - /mall-admin/captcha/check
      - /mall-admin/system/admin/login
      - /mall-goods/goods/category/getCategoryAndMergedCategory
      - /mall-admin/homepage/index/data
      - /mall-admin/logistics/region/list
      - /mall-goods/front/goods/list
      - /mall-goods/front/goods/getGoodsById
      - /mall-member/member/register
      - /mall-member/captcha/get #验证码接口
      - /mall-member/captcha/check
      - /mall-member/member/login
      - /mall-payment/alipay/notify
      - /mall-file/file/upload
      - /mall-admin/system/admin/save