spring:
  #####nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: cn-gd-sz.starryfrp.com:22006 #配置nacos地址
  management:
    endpoints:
      web:
        exposure:
          include: '*'
  #rabbit mq
  rabbitmq:
    host: cn-gd-sz.starryfrp.com
    username: rabbitAdmin
    password: rabbit@123
    virtual-host: /
    port: 22630
    listener:
      direct:
        acknowledge-mode: manual #NONE（默认）：自动；AUTO：根据情况确认；MANUAL：手动确认
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true #开启重发
          max-attempts: 3 #重试次数
          initial-interval: 5000 #重试间隔(ms)
    publisher-confirm-type: correlated #开启发送者confirm机制,对应RabbitTemplate.ConfirmCallback接口
    publisher-returns: true #发送失败回退，对应RabbitTemplate.ReturnCallback接口
    template:
      mandatory: true

feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
  hystrix:
    enabled: false
ribbon:
  eager-load:
    enabled: true
    clients:
      - mall-file
      - mall-order
      - mall-member
      - mall-admin
      - mall-goods
      - mall-seckill
      - mall-security-oauth2
      - mall-log
      - mall-payment
      - mall-gateway
      - mall-coupon
      - mall-cart
      - mall-search

#支付宝支付配置
alipay:
  app-id: 9021000124697344
  private-key: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQCofhMcwrq1xM/n5EJJ6vtj5lg5I9E9B3Yq4eO0NVdc851R+28S8E0F2Cq9/IjYbm2q0VQ9pCbgAS3k70tPoMJEwH4X7ISFzDIZXHo44AgUzFQUfBWhzm6Z+K4NHGZ3ltU37mAstua9XDP4th2zDeIW+7MY9n1H7yE15WCsIYL+sUJrBI/8b2lYGIbKwDXQfFCNicSEbUxfsEjog7g8US7EAOfNxZ/f7i55WR+fEvTSlU2iaAdvDufX1+IJc/qF86X37ziqoDjIY2Xzyu8Rl1zNWLAT1s0tdBsnJqcpWljKfnbMCB/BMOu7msNEIE8s558dSwyL4NI9xHtfOeKR8fdLAgMBAAECggEBAIAflpL5NJdB+MKiHRIuYElAAHg610IsKVxEdy0ynqMtEMUlh/oDxt4Z2a6smLbTigspsIBLEdCmtOpwWHlNikxTf87baI6BjtsgKkSTfzGpioolLSHkYtAsfNW1cemgRbSJTJLT5jO6KD8I5R6iAPlvHmpuDSglG8DrEo7x0LWwgXiARncDV0FV11st2OOkYb+sAI1Od/zfPZ16qTTWnaHv/bJlwCPCZF8yl9AoFMKbuWtvN89Am0FUTbBQUc4pGAg4/UY7M6Bm4IJABRl8lVMOnh3TfwlsZuJXFMJeAih3sxu5r2cmMayg1GNJcb0y+Cfpl3X2PNCvFkhhaQ1YbbkCgYEA5n5Q7+orhTo+DiAvjWCyAnm0nH9vtvIn5lqOd0ZSj7N3OQTPyL8XYWeZQf7o0m+2UBOsK9dmHRWiaWLWamj1F56Z8UUAGlAlBywq71OfwwbNUpVMyK9BRPTAkGddm8/SODD1mYiqBmYcE4lluKw7w7uc9JwlVMAtk0AWANAA/10CgYEAuyNS/TaMacbRSb7IdyfHcRNDgycPCExzGZ8b3/5FapkbCjHvz9tb61qQ4hNV6W82cRjZB37bIv3COUNIPiFTSLC1Gd32FN2ad0mbkwQQAd9jEfAOt0uWSqnFfeptMZNFmFNYngqtM/dY7LRVjzB+yeVfS76yU7eglGxB9i2f7scCgYEAlSjLYebNkSL2w5dqjngz2kw+aERD3EVrMrQJnABjL2F5VunZOVUIYV10nXPD4WKvvbRtZ9W13D6C4uY2UZhoe4eEodEAVwbkX3bitgwMyF3fg4DgtsJLX79v2kM6HbnolbqBRYFeXlO3+aChtlenOWxxDw75TZYsKC2Bz7bL3nUCgYEAkTPoecbwjkaRL7pTy3jXHJrI4KPW2yaOjIvTUir2a67etztmCw72tJgyIOjF2XnMcVbJVzKMEAt7v3jAPk0XVSifbLG39hq4duRrTVhynzFYqptsn7aLp+Uw8vGJxlSyRG4vLXm1SMQcgJWwaYlEZ52NIrWVorWxaFjTmZNvLBMCgYEAnduWUGGH1rLrF/uhq2Bl840zo2FdJi0b3aNYrilYeRDA332gTCAZJ0/6pKQdrwOn338vutmBlGLnEn1dZf+ij/8uo3BhJWeHKyEG5icsHMgN5cJJZAHe1Fu1hubRgmizH0RqFaULf1vMCy5whPVME7ye+oc6qwOt0YsRAQg+/iQ=
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwcMuVlhLSH5e/VTAmtHd2qzhvSfDFIGls6GKKbB1iHMNM0aRnmKWvzBIBxU9iABvYssZjWlw8kO0CkQN4XHeRYgEtIIShMCyLiU50ZfV3E7g/pwjDz0jQJLTh4vhfkuEIq40+Por5ZbxiUx9cdoh0tSGk5rxc0+5gv9aJcwTRMIxRM8z1XfKjmXIpFI4r2p8DIRfCANXrn9y0TNyki3zSSjIz77tVYvTyoxan5RXhYzKIoNtT+vM39i9J474+XnaoteHMs48AaBiwDcPsIpxWiG58NLlJPDtieFqN7uMvb635DLr7W2StDztgbdDnBT5DX1QyWF5uXDELLrcy2sk9QIDAQAB
  gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  sign-type: RSA2
  charset: utf-8
  format: json
  notify-url: http://dud279.natappfree.cc/mall-payment/alipay/notify
  return-url:
  log-path:

seata:
  enabled: true
  application-id: mall-order
  tx-service-group: my-seata-tx-group
  # 是否自动开启数据源代理
  enable-auto-data-source-proxy: true
  # 数据源代理模式，使用AT模式
  data-source-proxy-mode: AT
  service:
    # 事务群组
    vgroupMapping:
      my-seata-tx-group: seata-server  # default 的值为集群的名字，在配置 seata service 的时候指定的
    grouplist:
      default: cn-gd-sz.starryfrp.com:46496
    enable-degrade: false
    # 全局事务开关
    disable-global-transaction: false
  # 配置中心，需要和 seata server 保持一致
  config:
    type: nacos
    nacos:
      namespace: "e1bb85c5-fba3-4b50-856e-42368d5efb7f"
      server-addr: "http://cn-gd-sz.starryfrp.com:22006"
      group: "SEATA_GROUP"
      username: "nacos"
      password: "nacos"
      data-id: "seata-nacos-config.properties"
  # 注册中心，需要和 seata server 保持一致
  #  registry:
  #    type: nacos
  #    nacos:
  #      application: seata-server
  #      group: "SEATA_GROUP"
  #      namespace: "e1bb85c5-fba3-4b50-856e-42368d5efb7f"
  #      username: "nacos"
  #      password: "nacos"
  #      server-addr: "http://cn-gd-sz.starryfrp.com:22006"
  #      cluster: seata-server

elk:
  kafka:
    appender:
      servers: 'cn-gd-sz.starryfrp.com:37822'
      topic: readygo-mall-logs
