#### spring相关配置
spring:
  application:
    name: mall-oauth2 #应用名称
  profiles:
    active: dev
  main: #允许bean重名
    allow-bean-definition-overriding: true
server:
  port: 8000


secure:
  ignored:
    urls: #安全路径白名单
      - /user/login
      - /captcha/get
      - /captcha/check
      - /oauth2/auth