#### spring相关配置
spring:
  application:
    name: mall-security-oauth2 #应用名称
  profiles:
    active: dev
  main: #允许bean重名
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
server:
  port: 8001

#logostash
logging:
  config: classpath:logback-spring.xml