spring:
  #####nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 49.234.85.17:8848 #配置nacos地址
  management:
    endpoints:
      web:
        exposure:
          include: '*'
  #####redis配置
  redis:
    host: 49.234.85.17
    port: 6379
    password: DJTReadyGO19930312!@#$legion
    timeout: 6000
    database: 2
    lettuce:
      shutdown-timeout: 100

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: false
ribbon:
  eager-load:
    enabled: true
    clients: mall-security-oauth2,mall-seckill,mall-gateway,mall-file,mall-goods,mall-coupon,mall-member,mall-admin,mall-cart,mall-order

elk:
  kafka:
    appender:
      servers: '192.168.72.129:9092'
      topic: readygo-mall-logs