spring:
  #####数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://49.234.85.17:3306/readygo-mall-member?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: DJTReadyGO19930312!@#$legion
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  #####nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 49.234.85.17:8848 #配置nacos地址
  management:
    endpoints:
      web:
        exposure:
          include: '*'
  #####redis配置
  redis:
    host: 49.234.85.17
    port: 6379
    password: DJTReadyGO19930312!@#$legion
    timeout: 6000
    database: 1
    lettuce:
      shutdown-timeout: 100
  #rabbit mq
  rabbitmq:
    host: 49.234.85.17
    username: rabbitAdmin
    password: rabbit@123
    virtual-host: /
    port: 5672
    listener:
      simple:
        retry:
          enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: false
ribbon:
  eager-load:
    enabled: true
    clients: mall-member,mall-file,mall-security-oauth2,mall-gateway,mall-goods,mall-coupon,mall-seckill,mall-admin,mall-cart,mall-order
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:**/*Mapper.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#seata:
#  enabled: true
#  application-id: mall-member
#  tx-service-group: fsp_tx_group
#  # 这里开启自动的数据源配置，否则后秒要自己手动配置
#  enable-auto-data-source-proxy: true
#  data-source-proxy-mode: AT
#  use-jdk-proxy: false
#  service:
#    vgroupMapping:
#      fsp_tx_group: default
#    grouplist:
#      default: 127.0.0.1:8091
#  config:
#    type: file # 配置中心为file模式

seata:
  enabled: true
  application-id: mall-order
  tx-service-group: default_tx_group
  # 是否自动开启数据源代理
  enable-auto-data-source-proxy: true
  # 数据源代理模式，使用AT模式
  data-source-proxy-mode: AT
  service:
    # 事务群组
    vgroupMapping:
      default_tx_group: default  # default 的值为集群的名字，在配置 seata service 的时候指定的
    grouplist:
      default: 49.234.85.17:8091
    enable-degrade: false
    # 全局事务开关
    disable-global-transaction: false
  # 配置中心，需要和 seata server 保持一致
  config:
    type: nacos
    nacos:
      namespace: "a361e8e8-d854-465a-ba3c-4119bf32e078"
      server-addr: "49.234.85.17:8848"
      group: "nacos-seata"
      username: "nacos"
      password: "nacos"
      data-id: "nacos-config.properties"
  # 注册中心，需要和 seata server 保持一致
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: "SEATA_GROUP"
      namespace: "a361e8e8-d854-465a-ba3c-4119bf32e078"
      username: "nacos"
      password: "nacos"
      server-addr: "49.234.85.17:8848"