#### spring相关配置
spring:
  application:
    name: mall-admin #应用名称
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
server:
  port: 8100

#### 验证码相关配置
aj:
  captcha:
    jigsaw: classpath:images/jigsaw  # 滑动验证，底图路径，不配置将使用默认图片
    pic-click: classpath:images/pic-click  # 滑动验证，底图路径，不配置将使用默认图片
    cache-type: redis # 保存到redis
    type: default
    water-mark:
    slip-offset: 10 # 校验滑动拼图允许误差偏移量(默认5像素)
    aes-status: true
    interference-options: 2
    history-data-clear-enable: true
    req-frequency-limit-enable: true # 接口请求次数一分钟限制是否开启 true|false
    req-get-lock-limit: 60 # 验证失败50次，get接口锁定
    req-get-lock-seconds: 60 # 验证失败后，锁定时间间隔
    req-get-minute-limit: 30 # get接口一分钟内请求数限制
    req-check-minute-limit: 30 # check接口一分钟内请求数限制