spring:
  #####nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: cn-gd-sz.starryfrp.com:22006 #配置nacos地址
  management:
    endpoints:
      web:
        exposure:
          include: '*'

feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
  hystrix:
    enabled: false
ribbon:
  eager-load:
    enabled: true
    clients:
      - mall-file
      - mall-order
      - mall-member
      - mall-admin
      - mall-goods
      - mall-seckill
      - mall-security-oauth2
      - mall-log
      - mall-payment
      - mall-gateway
      - mall-coupon
      - mall-cart
      - mall-search

elk:
  kafka:
    appender:
      servers: 'cn-gd-sz.starryfrp.com:37822'
      topic: readygo-mall-logs