server:
  port: 8011
#### spring相关配置
spring:
  application:
    name: mall-search #应用名称
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

#logostash
logging:
  config: classpath:logback-spring.xml

