spring:
  #####nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: cn-gd-sz.starryfrp.com:22006 #配置nacos地址
  management:
    endpoints:
      web:
        exposure:
          include: '*'
  elasticsearch:
    rest:
      uris: cn-gd-sz.starryfrp.com:15340
  #rabbit mq
  rabbitmq:
    host: cn-gd-sz.starryfrp.com
    username: rabbitAdmin
    password: rabbit@123
    virtual-host: /
    port: 22630
    listener:
      direct:
        acknowledge-mode: manual #NONE（默认）：自动；AUTO：根据情况确认；MANUAL：手动确认
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true #开启重发
          max-attempts: 3 #重试次数
          initial-interval: 5000 #重试间隔(ms)
    publisher-confirm-type: correlated #开启发送者confirm机制,对应RabbitTemplate.ConfirmCallback接口
    publisher-returns: true #发送失败回退，对应RabbitTemplate.ReturnCallback接口
    template:
      mandatory: true
feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
  hystrix:
    enabled: false
ribbon:
  eager-load:
    enabled: true
    clients:
      - mall-file
      - mall-order
      - mall-member
      - mall-admin
      - mall-goods
      - mall-seckill
      - mall-security-oauth2
      - mall-log
      - mall-payment
      - mall-gateway
      - mall-coupon
      - mall-cart
      - mall-search

elk:
  kafka:
    appender:
      servers: 'cn-gd-sz.starryfrp.com:37822'
      topic: readygo-mall-logs

xxl:
  job:
    admin:
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。
      # 执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://127.0.0.1:8020/xxl-job-admin
    # 执行器通讯TOKEN [选填]：非空时启用；
    accessToken:
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: mall-search-executor
      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。
      #从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；
      # 地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip: 127.0.0.1
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9909
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: D:\\
      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 3
